# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zgd/Desktop/ciotfly

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zgd/Desktop/ciotfly

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zgd/Desktop/ciotfly/CMakeFiles /home/zgd/Desktop/ciotfly/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zgd/Desktop/ciotfly/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ciotfly

# Build rule for target.
ciotfly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ciotfly
.PHONY : ciotfly

# fast build rule for target.
ciotfly/fast:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/build
.PHONY : ciotfly/fast

src/analy.o: src/analy.c.o

.PHONY : src/analy.o

# target to build an object file
src/analy.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/analy.c.o
.PHONY : src/analy.c.o

src/analy.i: src/analy.c.i

.PHONY : src/analy.i

# target to preprocess a source file
src/analy.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/analy.c.i
.PHONY : src/analy.c.i

src/analy.s: src/analy.c.s

.PHONY : src/analy.s

# target to generate assembly for a file
src/analy.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/analy.c.s
.PHONY : src/analy.c.s

src/ancom.o: src/ancom.c.o

.PHONY : src/ancom.o

# target to build an object file
src/ancom.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/ancom.c.o
.PHONY : src/ancom.c.o

src/ancom.i: src/ancom.c.i

.PHONY : src/ancom.i

# target to preprocess a source file
src/ancom.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/ancom.c.i
.PHONY : src/ancom.c.i

src/ancom.s: src/ancom.c.s

.PHONY : src/ancom.s

# target to generate assembly for a file
src/ancom.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/ancom.c.s
.PHONY : src/ancom.c.s

src/app_user.o: src/app_user.c.o

.PHONY : src/app_user.o

# target to build an object file
src/app_user.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/app_user.c.o
.PHONY : src/app_user.c.o

src/app_user.i: src/app_user.c.i

.PHONY : src/app_user.i

# target to preprocess a source file
src/app_user.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/app_user.c.i
.PHONY : src/app_user.c.i

src/app_user.s: src/app_user.c.s

.PHONY : src/app_user.s

# target to generate assembly for a file
src/app_user.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/app_user.c.s
.PHONY : src/app_user.c.s

src/cetc_sock.o: src/cetc_sock.c.o

.PHONY : src/cetc_sock.o

# target to build an object file
src/cetc_sock.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/cetc_sock.c.o
.PHONY : src/cetc_sock.c.o

src/cetc_sock.i: src/cetc_sock.c.i

.PHONY : src/cetc_sock.i

# target to preprocess a source file
src/cetc_sock.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/cetc_sock.c.i
.PHONY : src/cetc_sock.c.i

src/cetc_sock.s: src/cetc_sock.c.s

.PHONY : src/cetc_sock.s

# target to generate assembly for a file
src/cetc_sock.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/cetc_sock.c.s
.PHONY : src/cetc_sock.c.s

src/client_tcp.o: src/client_tcp.c.o

.PHONY : src/client_tcp.o

# target to build an object file
src/client_tcp.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/client_tcp.c.o
.PHONY : src/client_tcp.c.o

src/client_tcp.i: src/client_tcp.c.i

.PHONY : src/client_tcp.i

# target to preprocess a source file
src/client_tcp.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/client_tcp.c.i
.PHONY : src/client_tcp.c.i

src/client_tcp.s: src/client_tcp.c.s

.PHONY : src/client_tcp.s

# target to generate assembly for a file
src/client_tcp.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/client_tcp.c.s
.PHONY : src/client_tcp.c.s

src/iotfly.o: src/iotfly.c.o

.PHONY : src/iotfly.o

# target to build an object file
src/iotfly.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/iotfly.c.o
.PHONY : src/iotfly.c.o

src/iotfly.i: src/iotfly.c.i

.PHONY : src/iotfly.i

# target to preprocess a source file
src/iotfly.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/iotfly.c.i
.PHONY : src/iotfly.c.i

src/iotfly.s: src/iotfly.c.s

.PHONY : src/iotfly.s

# target to generate assembly for a file
src/iotfly.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/iotfly.c.s
.PHONY : src/iotfly.c.s

src/log.o: src/log.c.o

.PHONY : src/log.o

# target to build an object file
src/log.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/log.c.o
.PHONY : src/log.c.o

src/log.i: src/log.c.i

.PHONY : src/log.i

# target to preprocess a source file
src/log.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/log.c.i
.PHONY : src/log.c.i

src/log.s: src/log.c.s

.PHONY : src/log.s

# target to generate assembly for a file
src/log.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/log.c.s
.PHONY : src/log.c.s

src/point_s.o: src/point_s.c.o

.PHONY : src/point_s.o

# target to build an object file
src/point_s.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/point_s.c.o
.PHONY : src/point_s.c.o

src/point_s.i: src/point_s.c.i

.PHONY : src/point_s.i

# target to preprocess a source file
src/point_s.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/point_s.c.i
.PHONY : src/point_s.c.i

src/point_s.s: src/point_s.c.s

.PHONY : src/point_s.s

# target to generate assembly for a file
src/point_s.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/point_s.c.s
.PHONY : src/point_s.c.s

src/serial_usb_com.o: src/serial_usb_com.c.o

.PHONY : src/serial_usb_com.o

# target to build an object file
src/serial_usb_com.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/serial_usb_com.c.o
.PHONY : src/serial_usb_com.c.o

src/serial_usb_com.i: src/serial_usb_com.c.i

.PHONY : src/serial_usb_com.i

# target to preprocess a source file
src/serial_usb_com.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/serial_usb_com.c.i
.PHONY : src/serial_usb_com.c.i

src/serial_usb_com.s: src/serial_usb_com.c.s

.PHONY : src/serial_usb_com.s

# target to generate assembly for a file
src/serial_usb_com.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/serial_usb_com.c.s
.PHONY : src/serial_usb_com.c.s

src/server_sock.o: src/server_sock.c.o

.PHONY : src/server_sock.o

# target to build an object file
src/server_sock.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/server_sock.c.o
.PHONY : src/server_sock.c.o

src/server_sock.i: src/server_sock.c.i

.PHONY : src/server_sock.i

# target to preprocess a source file
src/server_sock.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/server_sock.c.i
.PHONY : src/server_sock.c.i

src/server_sock.s: src/server_sock.c.s

.PHONY : src/server_sock.s

# target to generate assembly for a file
src/server_sock.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/server_sock.c.s
.PHONY : src/server_sock.c.s

src/signal.o: src/signal.c.o

.PHONY : src/signal.o

# target to build an object file
src/signal.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/signal.c.o
.PHONY : src/signal.c.o

src/signal.i: src/signal.c.i

.PHONY : src/signal.i

# target to preprocess a source file
src/signal.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/signal.c.i
.PHONY : src/signal.c.i

src/signal.s: src/signal.c.s

.PHONY : src/signal.s

# target to generate assembly for a file
src/signal.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/signal.c.s
.PHONY : src/signal.c.s

src/threadi.o: src/threadi.c.o

.PHONY : src/threadi.o

# target to build an object file
src/threadi.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/threadi.c.o
.PHONY : src/threadi.c.o

src/threadi.i: src/threadi.c.i

.PHONY : src/threadi.i

# target to preprocess a source file
src/threadi.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/threadi.c.i
.PHONY : src/threadi.c.i

src/threadi.s: src/threadi.c.s

.PHONY : src/threadi.s

# target to generate assembly for a file
src/threadi.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/threadi.c.s
.PHONY : src/threadi.c.s

src/unidimensional.o: src/unidimensional.c.o

.PHONY : src/unidimensional.o

# target to build an object file
src/unidimensional.c.o:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/unidimensional.c.o
.PHONY : src/unidimensional.c.o

src/unidimensional.i: src/unidimensional.c.i

.PHONY : src/unidimensional.i

# target to preprocess a source file
src/unidimensional.c.i:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/unidimensional.c.i
.PHONY : src/unidimensional.c.i

src/unidimensional.s: src/unidimensional.c.s

.PHONY : src/unidimensional.s

# target to generate assembly for a file
src/unidimensional.c.s:
	$(MAKE) -f CMakeFiles/ciotfly.dir/build.make CMakeFiles/ciotfly.dir/src/unidimensional.c.s
.PHONY : src/unidimensional.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ciotfly"
	@echo "... src/analy.o"
	@echo "... src/analy.i"
	@echo "... src/analy.s"
	@echo "... src/ancom.o"
	@echo "... src/ancom.i"
	@echo "... src/ancom.s"
	@echo "... src/app_user.o"
	@echo "... src/app_user.i"
	@echo "... src/app_user.s"
	@echo "... src/cetc_sock.o"
	@echo "... src/cetc_sock.i"
	@echo "... src/cetc_sock.s"
	@echo "... src/client_tcp.o"
	@echo "... src/client_tcp.i"
	@echo "... src/client_tcp.s"
	@echo "... src/iotfly.o"
	@echo "... src/iotfly.i"
	@echo "... src/iotfly.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/point_s.o"
	@echo "... src/point_s.i"
	@echo "... src/point_s.s"
	@echo "... src/serial_usb_com.o"
	@echo "... src/serial_usb_com.i"
	@echo "... src/serial_usb_com.s"
	@echo "... src/server_sock.o"
	@echo "... src/server_sock.i"
	@echo "... src/server_sock.s"
	@echo "... src/signal.o"
	@echo "... src/signal.i"
	@echo "... src/signal.s"
	@echo "... src/threadi.o"
	@echo "... src/threadi.i"
	@echo "... src/threadi.s"
	@echo "... src/unidimensional.o"
	@echo "... src/unidimensional.i"
	@echo "... src/unidimensional.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

